import React from 'react'
import Head from 'next/head'
import Link from 'next/link'

export default function Layout({ children, title }) {
    return (
        <>
            <Head>
                <title>{title ? title + ' - Ecommerce': 'E-Commerace'}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className='flex min-h-screen flex-col justify-between'>
                <header>
                    <nav className='flex h-12 item-center px-4 justify-between shadow-md'>
                        <Link href="/">
                            <p className='text-lg font-bold'>E-Commerace</p>
                        </Link>
                        <div>
                            <Link href="/cart" className='p-2'>Cart</Link>
                            <Link href="/login" className='p-2'>Login</Link>
                        </div>
                    </nav>
                </header>
                <main className='container m-auto mt-4 px-4'>
                    {children}
                </main>
                <footer className='flex h-10 justify-center item-center shadow-inner'>
                    <p>Copyright 2022 Ecommerace</p>
                </footer>
            </div>
        </>
    )
}
